### ISSUE TITLE
Add a load comments button

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/next-article#504] opened 2015-05-26 19:00 UTC
> I see no way to measure the effectiveness of this component. I suggested only loading comments if the user clicks a 'load comments' via a prominent button. Much easier to make a call in q3 about active usage/engagement.

https://github.com/Financial-Times/next-feature-flags-api/pull/165

**Comment by matthew-andrews** [comment] 2015-05-26 19:03
And give `articleComments` an end of Q3 expiry date.

**Comment by ironsidevsquincy** [comment] 2015-05-27 08:55
Remember we are collecting [comments interactions](https://beacon.ft.com/components?title=In%20the%20last%2024%20hours...&metric=funnel&timeframe=this_24_hours&steps=commentsComponent), but obviously doesn't capture read only users

There's a 'load more' button we could add tracking too in the meantime

**Comment by i-like-robots** [comment] 2016-03-24 20:29
Dupe of https://github.com/Financial-Times/next-article/issues/1199

**Closed by i-like-robots** 2016-03-24 20:29 UTC
